# Pipeline for test the changes in all branches except main

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: rununittest
  displayName: Run unit tests build and push in container registry
  jobs:
  - job: runTests
    displayName: Run Unit Tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseDotNet@2
        displayName: dotnet install
        inputs:
          packageType: 'sdk'
          version: '3.1.x'
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'config'
          nugetConfigPath: 'NuGet.config'
      - task: DotNetCoreCLI@2
        displayName: dotnet build
        inputs:
          command: 'build'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: dotnet test
        inputs:
          command: 'test'
          projects: '**/*[Tt]ests/*.csproj'